name: bukak_festival
description: "bukakFestival"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.1.0
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  assets:
    - assets/images/
    - assets/vectors/
    - assets/booths.json
    - assets/subBooths.json
    - assets/fonts/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular-subset.woff2
          weight: 400
        - asset: assets/fonts/NotoSansKR-SemiBold-subset.woff2
          weight: 600


  uses-material-design: true
